pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        // Si le système est de type Unix
                        sh 'make'
                    } else {
                        // Si le système est Windows
                        bat 'make'
                    }
                }
            }
        }

        stage('Permissions') {
            when {
                expression { isUnix() } // Ce stage ne sera exécuté que sur des systèmes Unix
            }
            steps {
                script {
                    sh 'chmod +x string_inverser' // donner les droits d'exécution sur le binaire
                }
            }
        }

        stage('Nettoyage') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'make clean' // Nettoyage sur Unix
                    } else {
                        bat 'make clean' // Nettoyage sur Windows
                    }
                }
            }
        }
    }
}
